
// ConsoleApp.Day1.Parts.One();
// ConsoleApp.Day1.Parts.Two();
// ConsoleApp.Day2.Parts.One();
// ConsoleApp.Day2.Parts.Two();
// ConsoleApp.Day3.Parts.One();
// ConsoleApp.Day3.Parts.Two();
// ConsoleApp.Day4.Parts.One();
// ConsoleApp.Day4.Parts.Two();
// ConsoleApp.Day5.Parts.One();
// ConsoleApp.Day5.Parts.Two();
// ConsoleApp.Day5.Parts.TwoBruteForce();
// ConsoleApp.Day6.Parts.One();
// ConsoleApp.Day6.Parts.Two();
// ConsoleApp.Day7.Parts.One(); 
// ConsoleApp.Day7.Parts.Two();
// ConsoleApp.Day8.Parts.One(); 
// ConsoleApp.Day8.Parts.Two();
// ConsoleApp.Day9.Parts.One(); 
// ConsoleApp.Day9.Parts.Two();
// ConsoleApp.Day10.Parts.One(); 
// ConsoleApp.Day10.Parts.Two();
// ConsoleApp.Day11.Parts.One(); 
// ConsoleApp.Day11.Parts.Two();
// ConsoleApp.Day12.Parts.One(); 
// ConsoleApp.Day12.Parts.Two();
// ConsoleApp.Day13.Parts.One(); 
// ConsoleApp.Day13.Parts.Two();
ConsoleApp.Day14.Parts.One(); 
ConsoleApp.Day14.Parts.Two();
